### ISSUE TITLE
Baseline results

### ISSUE THREAD

**Issue by amritbhanu** [ai-se/LAS-Phishing#2]
## Experiment
- Comparison against 7 learners: linear svm, rbf svm, LR, 8-NN, NB, RF, DR.
- 5 evaluation measures
- 25 repeats. 20% training and 80% testing.
- raw data distribution: non-phished:phished: 5:6

## Results
- All Features
![file](https://github.com/ai-se/LAS-Phishing/raw/master/results/Graph.png)

- Feature selections from weka: Prefix_Suffix, having_Sub_Domain, SSLfinal_State, Request_URL, URL_of_Anchor, Links_in_tags, SFH, web_traffic and Google_Index
![file](https://github.com/ai-se/LAS-Phishing/raw/master/results/Graph_less.png)

**Comment by amritbhanu** [comment]
- Important Attributes:
   - Prefix_Suffix, having_Sub_Domain, SSLfinal_State, Request_URL, URL_of_Anchor,  Links_in_tags, SFH, web_traffic and Google_Index

![file](https://github.com/ai-se/LAS-Phishing/raw/master/dataset/phishing.png)

**Comment by amritbhanu** [comment]
Data Dictionary - https://archive.ics.uci.edu/ml/machine-learning-databases/00327/

**Comment by timm** [comment]
BTW:
